language: php
sudo: true
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0.2
  - hhvm
matrix:
  allow_failures:
  - php: 7.0.2
  - php: 5.6
  - php: hhvm
env:
#  global:
#    - MAGENTO_DB_ALLOWSAME=1
#    - SKIP_CLEANUP=1
  - MAGENTO_VERSION=magento-mirror-1.9.1.0
  - MAGENTO_VERSION=magento-mirror-1.8.1.0
  - MAGENTO_VERSION=magento-mirror-1.8.0.0
  - MAGENTO_VERSION=magento-mirror-1.7.0.2
script:
  - curl -sSL https://raw.githubusercontent.com/AOEpeople/MageTestStand/master/setup.sh | bash
notifications:
  email:
    recipients:
      - pott@wabsolute.de
      - alexejenko@wabsolute.de
    on_success: always
    on_failure: always